Add the information on the WoT Japanese CG to wot-arketing/cg
w3c/wot-marketing pull request #128
Opened 2021-02-23 17:34 UTC by ashimura

2021-02-23 23:56 UTC, k-toumura approved these changes
Thank you, @ashimura .   It looks good to me.
We should upload a CG charter text as soon as possible...

2021-02-24 01:53 UTC, ashimura commented
@k-toumura that is a good question :)
Meanwhile, I've just changed the index.html to refer to the [WoT-JP CG page](https://www.w3.org/community/wot-jp/) for the "CG Scope" link tentatively.

We can change the URL again once the CG Charter is installed appropriately :)

2021-02-24 12:16 UTC, danielpeintner requested changes
Looks good. Just 2 minor typos that we should fix before merging.

2021-02-24 12:16 UTC, danielpeintner commented on docs/cg/index.html
> +		<li>Web of Things Japanese Commuity Group</li>
twice a minor type --> "Community"

2021-02-24 12:49 UTC, ashimura commented on docs/cg/index.html
> +		<li>Web of Things Japanese Commuity Group</li>
typos have been fixed :)

2021-02-24 12:55 UTC, sebastiankb commented
I had a brief chat with @ashimura and it's ok to merge this PR.

2021-02-24 12:55 UTC, merged