add zh_CN translation for subtitles (#141)
w3c/wot-marketing pull request #149
Opened 2021-03-09 16:50 UTC by lmy441900

This PR adds Simplified Chinese translations for the subtitles of WoT Explainer video.

There are still a few problems regarding to diction, e.g. the interpretation of "Things", "methodology", etc. I'll double check with W3C China people; suggestions are also welcomed in the comment as well.

2021-03-12 09:58 UTC, xfq commented
Note that `zh-Hans` is the proper BCP 47 language tag for Simplified Chinese. (See https://github.com/WICG/handwriting-recognition/issues/1#issuecomment-734812189 for the reason of it.)

2021-03-12 10:01 UTC, xfq commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +他希望让他的网页开发者们
这里「网站开发者」是不是比「网页开发者」更好一些？

2021-03-12 16:03 UTC, siusin requested changes
Almost Perfect! Thank you @lmy441900 .

2021-03-12 16:03 UTC, siusin commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +计量单位、数据类型、互动方式、安全、关系
互动方式 -> 交互

2021-03-12 16:03 UTC, siusin commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +当然了，WoT 就是他们要用的方法！
“就是将来他们选择要用的技术”是不是顺一点？

2021-03-15 11:15 UTC, lmy441900 commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +他希望让他的网页开发者们
是的。

2021-03-15 11:26 UTC, lmy441900 commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +某个网站上的天气预报数据
“实时更新”没有体现在原文里（虽然确实有这个意思）。

2021-03-15 11:29 UTC, lmy441900 commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +当然了，WoT 就是他们要用的方法！
这里有一个关于如何解释“methodology”的问题；不管原义的话确实是可取的。

2021-03-15 13:24 UTC, xfq approved these changes

2021-03-15 14:11 UTC, siusin commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +某个网站上的天气预报数据
嗯嗯，或者直接“在线更新”的就好，不然有点不明白为什么要强制用web天气服务

2021-03-15 14:12 UTC, siusin commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +当然了，WoT 就是他们要用的方法！
啊，看懂了，“WoT 就是他们要继续选用的方法”这样？

2021-03-16 11:54 UTC, lmy441900 commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +某个网站上的天气预报数据
原文是“Weather forecast data from an online web service”；我倾向于维持原译法。

2021-03-16 14:11 UTC, siusin commented on videos/WoT-Explainer-Video/WOTMotion.zh_CN.vtt
> +当然了，WoT 就是他们要用的方法！
好的，那我先merge啦～

2021-03-16 14:11 UTC, siusin approved these changes
Thank you!

2021-03-16 14:11 UTC, merged