Blog prep - animation announcement
w3c/wot-marketing pull request #158
Opened 2021-04-08 20:46 UTC by mmccool

- Move blog draft to "posts" directory and do some reord
- Convert proposed blog post announcing web page and animation to HTML
- Add links for images (thumbnail of video points to existing thumbnail, I will submit another PR against the web page for the web page screen shot) - (will add link here when that PR is ready)
- Clean up grammar as discussed in main call April 7
- Update blog README to reference review policy

Upon reviewing the publication policy I realized that it said a resolution was required, but I explicitly said we would NOT be doing resolutions in the April 7 call (and indeed, as expected, the turnout was low during Easter).  So although I think this is a statement of fact and non-controversial, I don't want to violate the policy myself right after setting it up, so will hold off until we can have a resolution in the next main call.  As it happens, I did make quite a few changes (which need review) and also need time to get the image in the right place so I can use it.

2021-04-12 11:53 UTC, egekorkan approved these changes

2021-04-13 09:43 UTC, sebastiankb approved these changes
Just small comment above. Also ok to submit this blog post as is.

2021-04-13 11:35 UTC, sebastiankb requested changes

2021-04-13 11:35 UTC, sebastiankb commented on posts/draft/2021-04-animation-webpage.html
> +This animation shows how a web developer can implement Internet of Things solutions while being interoperable and not locked into frameworks.
from today's marketing call: ... not locked into vendor specific frameworks.
Resolution is done in tomorrow's main call.

2021-04-14 21:01 UTC, merged