Add dart_wot to list of WoT Implementations
w3c/wot-marketing pull request #289
Opened 2022-03-28 14:06 UTC by JKRhb

As briefly discussed in today's Scripting Call, this PR adds [`dart_wot`](https://pub.dev/packages/dart_wot) (a Scriping API implementation written in Dart) to the list of implementations on the WoT website.

2022-03-28 15:23 UTC, danielpeintner requested changes
for consistency reasons I would argue we should have bracket ("(" and ")") around the description since all the other items do have that.

2022-03-28 15:31 UTC, danielpeintner commented on docs/developers/index.html
> +			<a href="https://pub.dev/packages/dart_wot" target="_blank">dart_wot</a> W3C Web of Things implementation written in Dart with support for HTTP and CoAP.
👍

2022-03-28 19:37 UTC, egekorkan commented
Any idea why netlify says "Failed during stage 'checking build content for changes': Canceled build due to no content change". Otherwise the change is ok for me

2022-03-28 19:41 UTC, JKRhb commented
> Any idea why netlify says "Failed during stage 'checking build content for changes': Canceled build due to no content change".

I think this is probably caused by the fact that I squashed the commits. Therefore it didn't detect any changes on the last run in comparison to the (now non-existent) commit before. Can you rerun the preview manually?

2022-03-28 19:57 UTC, egekorkan commented
Same problem but https://deploy-preview-289--wot-marketing.netlify.app/developers/ shows the changes

LGTM :)

2022-03-29 06:18 UTC, danielpeintner approved these changes

2022-03-29 11:12 UTC, merged